version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: keycloak
    command:
      [
          'start-dev',
          '--import-realm',
          '--spi-theme-static-max-age=-1',
          '--spi-theme-cache-themes=false',
          '--spi-theme-cache-templates=false'
      ]
    volumes:
      - ./realm-config:/opt/keycloak/data/import
      - ./customTheme:/opt/keycloak/themes
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts
      - KEYCLOAK_ADMIN=admin
      - KC_HTTP_PORT=9080
      - KC_HTTPS_PORT=9443
    ports:
      - 9080:9080
      - 9443:9443
