version: '3'
services:
  create_certs:
    container_name: create_certs
    image: elasticsearch:6.8.16
    command: >
      bash -c '
        if [[ ! -f ./config/certificates/elastic-certificates.p12 ]]; then
          bin/elasticsearch-certutil cert -out config/certificates/elastic-certificates.p12 -pass ""
        fi;
        chown -R 1000:0 /usr/share/elasticsearch/config/certificates
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: [ '${CERTS_DIR}:/usr/share/elasticsearch/config/certificates' ]